 # Publish all joint states -----------------------------------
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50


  # Position Controllers ---------------------------------------
  joint_front_left_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: FL_hip_joint
      pid:   {p: 100.0, i: 0.0, d: 5.0}
      antiwindup: False
  joint_front_left_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: FL_thigh_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False       
  joint_front_left_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: FL_calf_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0} 
      antiwindup: False
  joint_front_right_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: FR_hip_joint
      pid:   {p: 100.0, i: 0.0, d: 5.0} 
      antiwindup: False
  joint_front_right_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: FR_thigh_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False
  joint_front_right_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: FR_calf_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False
  joint_rear_left_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: RL_hip_joint
      pid:   {p: 100.0, i: 0.0, d: 5.0}
      antiwindup: False
  joint_rear_left_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: RL_thigh_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False
  joint_rear_left_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: RL_calf_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False
  joint_rear_right_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: RR_hip_joint
      pid:   {p: 100.0, i: 0.0, d: 5.0}
      antiwindup: False
  joint_rear_right_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: RR_thigh_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False
  joint_rear_right_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: RR_calf_joint
      pid:   {p: 300.0, i: 0.0, d: 8.0}
      antiwindup: False

