 # Publish all joint states -----------------------------------
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50


  # Position Controllers ---------------------------------------
  joint_front_left_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_left_hip
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_front_left_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_left_upper_leg
      pid: {p: 17, d: 0.95, i: 1.0} 
      antiwindup: True       
  joint_front_left_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_left_lower_leg
      pid: {p: 17, d: 0.95, i: 1.0} 
      antiwindup: True
  joint_front_right_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_right_hip
      pid: {p: 17, d: 0.95, i: 1.0} 
      antiwindup: True
  joint_front_right_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_right_upper_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_front_right_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_front_right_lower_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_left_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_left_hip
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_left_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_left_upper_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_left_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_left_lower_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_right_hip_x_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_right_hip
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_right_hip_y_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_right_upper_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True
  joint_rear_right_knee_controller:
      type:  effort_controllers/JointPositionController
      joint: motor_back_right_lower_leg
      pid: {p: 17, d: 0.95, i: 1.0}
      antiwindup: True

